export const REQUEST_DATA = 'REQUEST_DATA'
export const RECEIVE_DATA_SUCCESS = 'RECEIVE_DATA_SUCCESS'
export const RECEIVE_DATA_FAIL = 'RECEIVE_DATA_FAIL'
export const CLEAR_RESULTS = 'CLEAR_RESULTS'
